services:
  - type: web
    name: webhook-dayan
    runtime: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn webhook_base:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: CLIENT_TOKEN
        sync: false
    autoDeploy: true
{
  "message": "holding teste-dayan"
}
